routes/web.php
<?php

use App\Hotel;
use App\LocationDistrict;
use App\LocationDivision;
use App\Role;
use App\User;
use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','CustomerController@index')->name('customer_index');
Route::get('/destinations','CustomerController@destinations')->name('customer_destinations');
Route::get('/about','CustomerController@about')->name('customer_about');
Route::get('/contract','CustomerController@contract')->name('customer_contract');
Route::get('/elements','CustomerController@elements')->name('customer_elements');
Route::get('/news','CustomerController@news')->name('customer_news');
Route::match(['get','post'],'/search','SearchController@search')->name('customer.search');
Route::match(['get','post'],'/search/show','SearchController@show')->name('customer.search.show');
Route::match(['get','post'],'/booking','CustomerBookingController@bookingPage')->name('customer.booking.index');
Route::match(['get','post'],'/booking/store','CustomerBookingController@bookingStore')->name('customer.booking.store');
Route::get('/profile/{id}','ProfileController@index')->name('profile.index');
Route::post('/profile/create','ProfileController@store')->name('profile.store');
Route::get('/profile/{id}/edit','ProfileController@edit')->name('profile.edit');

//Route::match(['get', 'post'], '/', function () {
////
//});

// manager Routes
//, 'middleware' => []

Route::get('manager/register','ManagerRegisterController@showRegistrationForm')->name('ManagerRegister');
Route::post('manager/register','ManagerRegisterController@register')->name('ManagerRegister');
Route::group(['prefix' => 'manager','middleware'=>['auth']], function()
{
    Route::get('/', 'ManagerDashboardController@index')->name('manager.dashboard.index');
    Route::resource('hotels', HotelController::class);
    Route::resource('rooms', RoomController::class);
    Route::get('/bookings/pay/{id}','BookingController@pay')->name('bookings.pay');
    Route::resource('bookings', BookingController::class);
    Route::get('/users','HotelCustomerController@index')->name('manager.customer.index');



});



// admin Routes
//, 'middleware' => []
Route::group(['prefix' => 'admin','middleware'=>['auth']], function()
{
    Route::get('/', 'AdminDashboardController@index')->name('admin.dashboard.index');
    Route::resource('divisions', 'LocationDivisionController');
    Route::resource('districts', 'LocationDistrictController');
    Route::resource('roles',RoleController::class);

    Route::get('/users/admins','UserController@admin')->name('users.admin');
    Route::get('/users/customers','UserController@customer')->name('users.customer');
    Route::get('/users/managers','UserController@manager')->name('users.manager');
    Route::resource('users',UserController::class );

    Route::resource('hotel_lists', AdminHotelController::class);
//Hotel to Room Routes
    Route::get('/hotel_lists/{id}/bookings/index/','AdminHoteltoRoomController@hotelBookings')->name('Admin.hotel.booking.index');
    Route::get('/hotel_lists/{id}/rooms/index/','AdminHoteltoRoomController@index')->name('Admin.hotel.rooms.index');
    Route::get('/hotel_lists/{id}/rooms/create','AdminHoteltoRoomController@create')->name('Admin.hotel.rooms.create');
    Route::post('/hotel_lists/{id}/rooms','AdminHoteltoRoomController@store')->name('Admin.hotel.rooms.store');
    Route::get('/hotel_lists/{id}/rooms/{room}','AdminHoteltoRoomController@show')->name('Admin.hotel.rooms.show');
    Route::get('/hotel_lists/{id}/rooms/{room}/edit','AdminHoteltoRoomController@edit')->name('Admin.hotel.rooms.edit');
    Route::put('/hotel_lists/{id}/rooms/{room}','AdminHoteltoRoomController@update')->name('Admin.hotel.rooms.update');
    Route::delete('/hotel_lists/{id}/rooms/{room}','AdminHoteltoRoomController@destroy')->name('Admin.hotel.rooms.destroy');

    Route::resource('room_lists', AdminRoomController::class);
    Route::get('/bookings','AdminBookingListController@index')->name('admin.booking.index');
});






Route::get('def','UserController@customer')->name('def');
Route::get('ghi','UserController@manager')->name('ghi');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');







// laravel default routes
//Route::get('/', function () {
//    return view('welcome');
//});



// testing and demo routes

Route::get('/testing/blade', function (Request $request) {
  return view('testing');
})->name('testing.blade');

Route::get('/testing', function (Request $request) {
    return redirect()->route('admin.booking.index');
});

//    Route::resources([
//        'hotels' => HotelController::class,
//        'hotel_facilities' => HotelFacilityController::class,
//
//
//    ]);

resources/views/backend/admin/division/create.blade.php
@extends('backend.layouts.master_tem')

@section('content')
    <div class="container">

        <div class="container" style="margin-bottom: 20px">
            <div style="text-align: justify">
                <a class="btn btn-secondary" href="{{route('divisions.index')}}">List of Divisions</a>
            </div>
            <h1 style="text-align:center;margin-bottom: 40px">Enter the Name of The Divisions</h1>

            @include('backend.layouts.errors')

            {!! Form::open(['route'=>'divisions.store']) !!}

            @include('backend.admin.division.form')



                <div class="col-4 text-left">
                    {!! Form::submit('Submit',['class'=>['btn','btn-primary'] ]) !!}
                </div>

            </div>

            {!! Form::close() !!}

        </div>

@endsection

resources/views/backend/admin/division/edit.blade.php
@extends('backend.layouts.master_tem')

@section('content')
    <div class="container">

        <div class="container" style="margin-bottom: 20px">
            <div style="text-align: justify">
                <a class="btn btn-secondary" href="{{route('divisions.index')}}">List of Divisions</a>
            </div>
            <h1 style="text-align:center;margin-bottom: 40px">Edit the info of The Divisions</h1>

            @include('backend.layouts.errors')

            {!! Form::model($division,[
                            'route'=>['divisions.update',$division->id],
                            'method' => 'put'
                            ]) !!}

            @include('backend.admin.division.form')



            <div class="col-4 text-left">
                {!! Form::submit('Update',['class'=>['btn','btn-primary'] ]) !!}
            </div>

        </div>

        {!! Form::close() !!}

    </div>

@endsection

resources/views/backend/admin/division/form.blade.php
<div class="form-row">
    <div class="col-4 text-right ">
        <h4>
        {!! Form::label('name','Division Name:') !!}
        </h4>
    </div>
    <div class="form-group col-4 text-center" >
        {!! Form::text('name',null,['class'=>'form-control','required']) !!}
    </div>

resources/views/backend/admin/division/index.blade.php
@extends('backend.layouts.master_tem')

@section('title', 'Division List')

@section('content')

    <h1 class="h3 mb-2 text-gray-800" style="text-align:center;">List of Divisions in Bangladesh</h1>
    @include('frontend.message')

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6   class="m-0 font-weight-bold text-primary"><a href="{{ route('divisions.create') }}" style="color:white;" class="btn btn-primary">Add Division</a></h6>
        </div>
        @if(count($divisions) == 0)
            <h3>No Record Found. Add some records</h3>
        @else
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>No.</th>
                        <th>name</th>
                        <th>Actions</th>
                    </tr>
                    </thead>

                    <tbody>
                    @php
                    $i = 0
                    @endphp
                    @foreach($divisions as $division)
                    <tr>
                        <td> {{++$i}}</td>
                        <td>{{ $division->name }}</td>

                        <td >


                            <a href="{{ route('divisions.edit', [$division->id]) }}" style="color:black;" class="btn btn-warning">
                                Edit
                            </a>

                            <form action="{{ route('divisions.destroy', [$division->id]) }}" method="post" style="display: inline">
                                @csrf
                                @method('delete')
                                <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure want to delete ?')">Delete</button>
                            </form>

                        </td>
                    </tr>
                    @endforeach

                    </tbody>
                </table>
            </div>
        </div>
        @endif
    </div>






























{{--            <h6 class="m-0 font-weight-bold text-primary float-left">List</h6>--}}
{{--            <a class="btn btn-primary float-right" href="{{ route('divisions.create') }}">Create</a>--}}


{{--            @include('layouts.message')--}}

{{--            <div class="table-responsive">--}}
{{--                <table class="table table-bordered"  width="100%" cellspacing="0">--}}
{{--                    <thead>--}}
{{--                    <tr>--}}
{{--                        --}}

{{--                    </tr>--}}
{{--                    </thead>--}}
{{--                    <tbody>--}}
{{--                    @foreach($divisions as $division)--}}
{{--                        <tr>--}}
{{--                            <td>{{ $division->name }}</td>--}}
{{--                           <td>--}}
{{--                                <a href="{{ route('divisions.show', [$division->id]) }}" class="btn btn-info">Show</a>--}}
{{--                                <a href="{{ route('divisions.edit', [$division->id]) }}" class="btn btn-warning">Edit</a>--}}

{{--                                <form action="{{ route('divisions.destroy', [$division->id]) }}" method="post" style="display: inline">--}}
{{--                                    @csrf--}}
{{--                                    @method('delete')--}}
{{--                                    <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure want to delete ?')">Delete</button>--}}
{{--                                </form>--}}

{{--                            </td>--}}
{{--                        </tr>--}}
{{--                    @endforeach--}}
{{--                    </tbody>--}}
{{--                </table>--}}
{{--            </div>--}}

{{--    </div>--}}
@endsection

resources/views/backend/admin/division/show.blade.php
<?php