routes/web.php
<?php

use App\Hotel;
use App\LocationDistrict;
use App\LocationDivision;
use App\Role;
use App\User;
use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','CustomerController@index')->name('customer_index');
Route::get('/destinations','CustomerController@destinations')->name('customer_destinations');
Route::get('/about','CustomerController@about')->name('customer_about');
Route::get('/contract','CustomerController@contract')->name('customer_contract');
Route::get('/elements','CustomerController@elements')->name('customer_elements');
Route::get('/news','CustomerController@news')->name('customer_news');
Route::match(['get','post'],'/search','SearchController@search')->name('customer.search');
Route::match(['get','post'],'/search/show','SearchController@show')->name('customer.search.show');
Route::match(['get','post'],'/booking','CustomerBookingController@bookingPage')->name('customer.booking.index');
Route::match(['get','post'],'/booking/store','CustomerBookingController@bookingStore')->name('customer.booking.store');
Route::get('/profile/{id}','ProfileController@index')->name('profile.index');
Route::post('/profile/create','ProfileController@store')->name('profile.store');
Route::get('/profile/{id}/edit','ProfileController@edit')->name('profile.edit');

//Route::match(['get', 'post'], '/', function () {
////
//});

// manager Routes
//, 'middleware' => []

Route::get('manager/register','ManagerRegisterController@showRegistrationForm')->name('ManagerRegister');
Route::post('manager/register','ManagerRegisterController@register')->name('ManagerRegister');
Route::group(['prefix' => 'manager','middleware'=>['auth']], function()
{
    Route::get('/', 'ManagerDashboardController@index')->name('manager.dashboard.index');
    Route::resource('hotels', HotelController::class);
    Route::resource('rooms', RoomController::class);
    Route::get('/bookings/pay/{id}','BookingController@pay')->name('bookings.pay');
    Route::resource('bookings', BookingController::class);
    Route::get('/users','HotelCustomerController@index')->name('manager.customer.index');



});



// admin Routes
//, 'middleware' => []
Route::group(['prefix' => 'admin','middleware'=>['auth']], function()
{
    Route::get('/', 'AdminDashboardController@index')->name('admin.dashboard.index');
    Route::resource('divisions', 'LocationDivisionController');
    Route::resource('districts', 'LocationDistrictController');
    Route::resource('roles',RoleController::class);

    Route::get('/users/admins','UserController@admin')->name('users.admin');
    Route::get('/users/customers','UserController@customer')->name('users.customer');
    Route::get('/users/managers','UserController@manager')->name('users.manager');
    Route::resource('users',UserController::class );

    Route::resource('hotel_lists', AdminHotelController::class);
//Hotel to Room Routes
    Route::get('/hotel_lists/{id}/bookings/index/','AdminHoteltoRoomController@hotelBookings')->name('Admin.hotel.booking.index');
    Route::get('/hotel_lists/{id}/rooms/index/','AdminHoteltoRoomController@index')->name('Admin.hotel.rooms.index');
    Route::get('/hotel_lists/{id}/rooms/create','AdminHoteltoRoomController@create')->name('Admin.hotel.rooms.create');
    Route::post('/hotel_lists/{id}/rooms','AdminHoteltoRoomController@store')->name('Admin.hotel.rooms.store');
    Route::get('/hotel_lists/{id}/rooms/{room}','AdminHoteltoRoomController@show')->name('Admin.hotel.rooms.show');
    Route::get('/hotel_lists/{id}/rooms/{room}/edit','AdminHoteltoRoomController@edit')->name('Admin.hotel.rooms.edit');
    Route::put('/hotel_lists/{id}/rooms/{room}','AdminHoteltoRoomController@update')->name('Admin.hotel.rooms.update');
    Route::delete('/hotel_lists/{id}/rooms/{room}','AdminHoteltoRoomController@destroy')->name('Admin.hotel.rooms.destroy');

    Route::resource('room_lists', AdminRoomController::class);
    Route::get('/bookings','AdminBookingListController@index')->name('admin.booking.index');
});






Route::get('def','UserController@customer')->name('def');
Route::get('ghi','UserController@manager')->name('ghi');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');







// laravel default routes
//Route::get('/', function () {
//    return view('welcome');
//});



// testing and demo routes

Route::get('/testing/blade', function (Request $request) {
  return view('testing');
})->name('testing.blade');

Route::get('/testing', function (Request $request) {
    return redirect()->route('admin.booking.index');
});

//    Route::resources([
//        'hotels' => HotelController::class,
//        'hotel_facilities' => HotelFacilityController::class,
//
//
//    ]);

app/Room.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Room extends Model
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [ 'hotel_id','number','type','single_beds','double_beds','max_person','price','TV','AC','bathtub','water_heater','refrigerator','wifi','coffee_tea_maker','other_facilities','photo'

         ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [

    ];

    public function hotel()
    {
        return $this->belongsTo(Hotel::class);
    }

    public function users()
    {
        return $this->belongsToMany( User::class);
    }


}

app/Http/Controllers/RoomController.php
<?php

namespace App\Http\Controllers;

use App\Hotel;
use App\Room;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class RoomController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        $hotel = Hotel::where('user_id','=',"$user->id")->first();
        $rooms =Room::where('hotel_id','=',"$hotel->id")->get();
        return view('backend.manager.room.index',compact('rooms'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = Auth::user();
        $hotel = Hotel::where('user_id','=',"$user->id")->first();
        return view('backend.manager.room.create',compact('hotel'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {

            $request->validate([
                'number' => 'required',
                'type' => 'required|',
                'single_beds' => 'required|numeric',
                'double_beds' => 'required|numeric',
                'price' => 'required|numeric',
                'TV' => 'required|',
                'AC' => 'required|',
                'bathtub' => 'required|',
                'water_heater' => 'required|',
                'refrigerator' => 'required|',
                'wifi' => 'required|',
                'coffee_tea_maker' => 'required|',
                'max_person' => 'required'
            ]);

            $data = $request->all();
            if ($request->hasFile('photo'))
            {
                $file = $request->file('photo');
                $extension = $file->getClientOriginalExtension();
                $filename = time().'.'.$extension;
                $file->move('uploads/rooms/',$filename);
                $data['photo'] = $filename;
            }
            else{
                return $request;
                $data['photo'] = "";

            }
            Room::create($data);
            return redirect()->route('rooms.index')->with('success','Room created Successfully.');


        }catch (QueryException $exception)
        {
            return redirect()->back()->with('error',$exception->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Room  $room
     * @return \Illuminate\Http\Response
     */
    public function show(Room $room)
    {
        $user = Auth::user();
        $hotel = Hotel::where('user_id','=',"$user->id")->first();
        return view('backend.manager.room.show',compact('room','hotel'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Room  $room
     * @return \Illuminate\Http\Response
     */
    public function edit(Room $room)
    {
        $user = Auth::user();
        $hotel = Hotel::where('user_id','=',"$user->id")->first();
        return view('backend.manager.room.edit',compact('room','hotel'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Room  $room
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Room $room)
    {
        try {


            $request->validate([
                'number' => 'required',
                'type' => 'required|',
                'single_beds' => 'required|numeric',
                'double_beds' => 'required|numeric',
                'price' => 'required|numeric',
                'TV' => 'required|',
                'AC' => 'required|',
                'bathtub' => 'required|',
                'water_heater' => 'required|',
                'refrigerator' => 'required|',
                'wifi' => 'required|',
                'coffee_tea_maker' => 'required|',

            ]);

            $data = $request->all();
            if ($request->hasFile('photo'))
            {
                $file = $request->file('photo');
                $extension = $file->getClientOriginalExtension();
                $filename = time().'.'.$extension;
                $file->move('uploads/rooms/',$filename);
                $data['photo'] = $filename;
            }
            else{
                return $request;
                $data['photo'] = "";
            }

            $room->update($data);
            return redirect()->route('rooms.index')->with('success','Room info has been updated successfully.');

        }
        catch (QueryException $exception) {
            return redirect()->back()->with('error',$exception->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Room  $room
     * @return \Illuminate\Http\Response
     */
    public function destroy(Room $room)
    {
        try {
            $room->delete();
            return redirect()->route('rooms.index')->withStatus('Room has been deleted successfully.');

        }
        catch (QueryException $exception) {
            return redirect()->back()->with('error',$exception->getMessage());
        }
    }
}

resources/views/backend/admin/room/create.blade.php
@extends('backend.layouts.master_tem')
@section('title','Admin: Room Create')

@section('content')

    <div class="container-fluid">


        <h1 style="text-align:center">Please Enter the Room Information and Facilities</h1>
        @php
        $hotel = \App\Hotel::where('id','=',"$id")->first();
        @endphp
        <h3 style="text-align: center;font-family: 'Times New Roman'">{{$hotel->name}} </h3>

        <div class="container" style="margin-bottom: 20px">

            {!! Form::open(['route'=>'room_lists.store']) !!}

            @include('backend.admin.room.form')

            <div class="form-row">
                <div class="col-4 text-center"></div>
                <div class="col-4 text-center">
                    {!! Form::submit('Add Your Hotel Room',['class'=>['btn','btn-primary'] ]) !!}
                </div>
                <div class="col-4 text-center"></div>

            </div>

            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/backend/admin/room/edit.blade.php
@extends('backend.layouts.master_tem')
@section('title' ,'Admin: Room Update')
@section('content')

    <div class="container-fluid">

        <h1 class="h3 mb-2 text-gray-800" style="text-align:center;">{{$hotel->name}}</h1>

        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6   class="m-0 font-weight-bold text-primary">
                    <a href="{{ route('room_lists.index' )}}" style="color:black;font-size: large" class="btn btn-info">List of Room</a>
                    <a href="{{ route('room_lists.edit',[$room->id]) }}" style="color:black;font-size: large" class="btn btn-warning">Edit the Room Info </a>
                </h6>
            </div>
        <h1 style="text-align:center">Change The Room info Here if You Want</h1>

        <div class="container" style="margin-bottom: 20px">

            {!! Form::model($room,[
                             'route'=>['room_lists.update',$room->id],
                             'method' => 'put','files' => true
                             ]) !!}
                @include('backend.admin.room.form')
                <div class="form-row">
                    <div class="form-group col-8">
                        @if(strpos("$room->photo","images.unsplash.com/"))
                            <img src="{{$room->photo}}" style="width: 100%;height:400px" alt="">
                        @else
                            <img src='{{asset("uploads/rooms/$room->photo")}}' style="width: 100%;height:400px" alt="">
                        @endif
                    </div>

                    <div class="form-group col-4" style="padding-top: 300px">
                        <strong> <label for="photo" class="text-danger">If you want to change the Room picture:</label></strong>
                        <input type="file" id="photo" name="photo" class="form-control">
                    </div>
                </div>
                <div style="text-align: center">
                    <input type="submit" class="btn btn-primary" value="Update the Room Info">
                </div>


            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/backend/admin/room/form.blade.php
<div class="form-row">
    <div class="form-group col-3">
        {!! Form::label('number','Room Number:') !!}
        {!! Form::text('number',null,['class'=>'form-control','required']) !!}
    </div>

    <div class="form-group col-3">
        {!! Form::label('type','Room Type:') !!}
        {!! Form::text('type',null,['class'=>'form-control','required']) !!}

    </div>

    <div class="form-group col-3">
        {!! Form::label('single_beds','How many single bed?') !!}
        {!! Form::number('single_beds',null,['class'=>'form-control','required','min'=>0]) !!}

    </div>

    <div class="form-group col-3">
        {!! Form::label('double_beds','How many double bed?') !!}
        {!! Form::number('double_beds',null,['class'=>'form-control','required','min'=>0]) !!}

    </div>
</div>

<div style="margin-top: 20px">
    <strong style="padding: 5px">Room Facilities</strong>
    <div class="form-row ">
            <div class="form-group col-3 text-center" >
                <h5>Television</h5>
                {!! Form::label('TV','yes') !!}
                {!! Form::radio('TV', '1') !!}<br>
                {!! Form::label('TV','No') !!}
                {!! Form::radio('TV', '0') !!}
            </div>

        <div class="form-group col-3 text-center" >
            <h5>Air Conditioner</h5>
            {!! Form::label('AC','yes') !!}
            {!! Form::radio('AC', '1') !!}<br>
            {!! Form::label('AC','No') !!}
            {!! Form::radio('AC', '0') !!}
        </div>

        <div class="form-group col-3 text-center" >
            <h5>Bathtub to take Bath</h5>
            {!! Form::label('bathtub','yes') !!}
            {!! Form::radio('bathtub', '1') !!}<br>
            {!! Form::label('bathtub','No') !!}
            {!! Form::radio('bathtub', '0') !!}
        </div>

        <div class="form-group col-3 text-center" >
            <h5>Water Heater</h5>
            {!! Form::label('water_heater','yes') !!}
            {!! Form::radio('water_heater', '1') !!}<br>
            {!! Form::label('water_heater','No') !!}
            {!! Form::radio('water_heater', '0') !!}
        </div>
    </div>
    <div class="form-group form-row">

        <div class="form-group col-4 text-center" >
            <h5>Refrigerator for Foods and Drinks</h5>
            {!! Form::label('refrigerator','yes') !!}
            {!! Form::radio('refrigerator', '1') !!}<br>
            {!! Form::label('refrigerator','No') !!}
            {!! Form::radio('refrigerator', '0') !!}
        </div>

        <div class="form-group col-4 text-center" >
            <h5>Machine for Coffee/Tea making</h5>
            {!! Form::label('coffee_tea_maker','yes') !!}
            {!! Form::radio('coffee_tea_maker', '1') !!}<br>
            {!! Form::label('coffee_tea_maker','No') !!}
            {!! Form::radio('coffee_tea_maker', '0') !!}
        </div>

        <div class="form-group col-4 text-center" >
            <h5>Free Wifi</h5>
            {!! Form::label('wifi','yes') !!}
            {!! Form::radio('wifi', '1') !!}<br>
            {!! Form::label('wifi','No') !!}
            {!! Form::radio('wifi', '0') !!}
        </div>

    <div class="form-row ">

        <div class="form-group col-6 text-center" >
            <strong>{!! Form::label('other_facilities','Details of other Facilities:') !!}</strong>
            {!! Form::textarea('other_facilities',null,['class'=>'form-control','rows'=>5,'placeholder'=>"If your hotel's room have other facilities,you can list them here."]) !!}

        </div>

        <div class="form-group col-4">
            <strong>{!! Form::label('price','Cost per Day in Bangladeshi Taka') !!}</strong>
            {!! Form::number('price',null,['class'=>'form-control','required','min'=>0]) !!}
        </div>

    </div>
</div>
    <input type="text" name="hotel_id" value="{{$hotel->id}}" hidden>


</div>

resources/views/backend/admin/room/index.blade.php
@extends('backend.layouts.master_tem')

@section('title', 'Admin: Room List')

@section('content')

    <h1 class="h3 mb-2 text-gray-800" style="text-align:center;">List of All Rooms</h1>


    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6   class="m-0 font-weight-bold text-primary"></h6>
        </div>
        @if(count($rooms) == 0)
            <h3>No Record Found. Add some records</h3>
        @else
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>No.</th>
                            <th>Room No.</th>
                            <th>Hotel</th>
                            <th>Type</th>
                            <th>Single Beds</th>
                            <th>Double Beds</th>
                            <th>Max Person</th>
                            <th>price(BDT)</th>
                            <th>Actions</th>
                        </tr>
                        </thead>

                        <tbody>
                        @php
                            $i = 0
                        @endphp
                        @foreach($rooms as $room)
                            <tr>
                                <td> {{++$i}}</td>
                                <td>{{$room->number}}</td>
                                @php
                                $hotel = \App\Hotel::where('id','=',"$room->hotel_id")->first();
                                @endphp
                                <td>{{$hotel->name}}</td>
                                <td>{{$room->type}}</td>
                                <td>{{$room->single_beds}}</td>
                                <td>{{$room->double_beds}}</td>
                                <td>{{$room->max_person}}</td>
                                <td>{{$room->price}}</td>
                                <td >
                                    <a href="{{ route('room_lists.show', [$room->id]) }}" style="color:black;" class="btn btn-info">
                                        Details
                                    </a>
                                    <a href="{{ route('room_lists.edit', [$room->id]) }}" style="color:black;" class="btn btn-warning">
                                        Edit
                                    </a>

                                    <form action="{{ route('room_lists.destroy', [$room->id]) }}" method="post" style="display: inline">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" disabled class="btn btn-danger" onclick="return confirm('Are you sure want to delete ?')">Delete</button>
                                    </form>

                                </td>
                            </tr>
                        @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        @endif
    </div>


@endsection

resources/views/backend/admin/room/show.blade.php
@extends('backend.layouts.master_tem')
@section('title','Admin: Room Details')
@section('content')
    <h1 class="h3 mb-2 text-gray-800" style="text-align:center;">{{$hotel->name}}</h1>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6   class="m-0 font-weight-bold text-primary">
                <a href="{{ route('room_lists.index' )}}" style="color:black;font-size: large" class="btn btn-info">List of Room</a>
                <a href="{{ route('room_lists.edit',[$room->id]) }}" style="color:black;font-size: large" class="btn btn-warning">Edit the Room Info </a>
            </h6>
        </div>

        <div class="container" style="margin-bottom: 20px">

            {!! Form::model($room,['action'=>null]) !!}

                @include('backend.admin.room.form')

            <div class="form-row">
                <div class="form-group col-12">
                    @if(strpos("$room->photo","images.unsplash.com/"))
                        <img src="{{$room->photo}}" style="width: 100%;height:400px" alt="">
                    @else
                        <img src='{{asset("uploads/rooms/$room->photo")}}' style="width: 100%;height:400px" alt="">
                    @endif
                </div>
            </div>
            <div class="form-row">
                <div class="col-12" style="text-align: center">
                    <strong>Image : {{$room->number}} </strong>
                </div>
            </div>

            {!! Form::close() !!}
        </div>

    </div>

@endsection