routes/web.php
<?php

use App\Hotel;
use App\LocationDistrict;
use App\LocationDivision;
use App\Role;
use App\User;
use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','CustomerController@index')->name('customer_index');
Route::get('/destinations','CustomerController@destinations')->name('customer_destinations');
Route::get('/about','CustomerController@about')->name('customer_about');
Route::get('/contract','CustomerController@contract')->name('customer_contract');
Route::get('/elements','CustomerController@elements')->name('customer_elements');
Route::get('/news','CustomerController@news')->name('customer_news');
Route::match(['get','post'],'/search','SearchController@search')->name('customer.search');
Route::match(['get','post'],'/search/show','SearchController@show')->name('customer.search.show');
Route::match(['get','post'],'/booking','CustomerBookingController@bookingPage')->name('customer.booking.index');
Route::match(['get','post'],'/booking/store','CustomerBookingController@bookingStore')->name('customer.booking.store');
Route::get('/profile/{id}','ProfileController@index')->name('profile.index');
Route::post('/profile/create','ProfileController@store')->name('profile.store');
Route::get('/profile/{id}/edit','ProfileController@edit')->name('profile.edit');

//Route::match(['get', 'post'], '/', function () {
////
//});

// manager Routes
//, 'middleware' => []

Route::get('manager/register','ManagerRegisterController@showRegistrationForm')->name('ManagerRegister');
Route::post('manager/register','ManagerRegisterController@register')->name('ManagerRegister');
Route::group(['prefix' => 'manager','middleware'=>['auth']], function()
{
    Route::get('/', 'ManagerDashboardController@index')->name('manager.dashboard.index');
    Route::resource('hotels', HotelController::class);
    Route::resource('rooms', RoomController::class);
    Route::get('/bookings/pay/{id}','BookingController@pay')->name('bookings.pay');
    Route::resource('bookings', BookingController::class);
    Route::get('/users','HotelCustomerController@index')->name('manager.customer.index');



});



// admin Routes
//, 'middleware' => []
Route::group(['prefix' => 'admin','middleware'=>['auth']], function()
{
    Route::get('/', 'AdminDashboardController@index')->name('admin.dashboard.index');
    Route::resource('divisions', 'LocationDivisionController');
    Route::resource('districts', 'LocationDistrictController');
    Route::resource('roles',RoleController::class);

    Route::get('/users/admins','UserController@admin')->name('users.admin');
    Route::get('/users/customers','UserController@customer')->name('users.customer');
    Route::get('/users/managers','UserController@manager')->name('users.manager');
    Route::resource('users',UserController::class );

    Route::resource('hotel_lists', AdminHotelController::class);
//Hotel to Room Routes
    Route::get('/hotel_lists/{id}/bookings/index/','AdminHoteltoRoomController@hotelBookings')->name('Admin.hotel.booking.index');
    Route::get('/hotel_lists/{id}/rooms/index/','AdminHoteltoRoomController@index')->name('Admin.hotel.rooms.index');
    Route::get('/hotel_lists/{id}/rooms/create','AdminHoteltoRoomController@create')->name('Admin.hotel.rooms.create');
    Route::post('/hotel_lists/{id}/rooms','AdminHoteltoRoomController@store')->name('Admin.hotel.rooms.store');
    Route::get('/hotel_lists/{id}/rooms/{room}','AdminHoteltoRoomController@show')->name('Admin.hotel.rooms.show');
    Route::get('/hotel_lists/{id}/rooms/{room}/edit','AdminHoteltoRoomController@edit')->name('Admin.hotel.rooms.edit');
    Route::put('/hotel_lists/{id}/rooms/{room}','AdminHoteltoRoomController@update')->name('Admin.hotel.rooms.update');
    Route::delete('/hotel_lists/{id}/rooms/{room}','AdminHoteltoRoomController@destroy')->name('Admin.hotel.rooms.destroy');

    Route::resource('room_lists', AdminRoomController::class);
    Route::get('/bookings','AdminBookingListController@index')->name('admin.booking.index');
});






Route::get('def','UserController@customer')->name('def');
Route::get('ghi','UserController@manager')->name('ghi');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');







// laravel default routes
//Route::get('/', function () {
//    return view('welcome');
//});



// testing and demo routes

Route::get('/testing/blade', function (Request $request) {
  return view('testing');
})->name('testing.blade');

Route::get('/testing', function (Request $request) {
    return redirect()->route('admin.booking.index');
});

//    Route::resources([
//        'hotels' => HotelController::class,
//        'hotel_facilities' => HotelFacilityController::class,
//
//
//    ]);

app/Hotel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Hotel extends Model
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name','user_id','division_id','district_id','local_address','telephone','mobile1','mobile2','star','free_breakfast','about_breakfast','private_parking','car_rental','swimming_pool','call_on_doctor','gym','restaurant','spa','meeting_room','other_facilities','photo'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [

    ];

    public function user()
    {
//        return $this->belongsTo(User::class);
        return $this->belongsTo('App\User');

    }
    public function division()
    {
        return $this->belongsTo(LocationDivision::class);
    }
    public function district()
    {
        return $this->belongsTo(LocationDistrict::class);
    }
    public function room()
    {
        return $this->hasMany(Room::class);
    }


}

app/Http/Controllers/HotelController.php
<?php

namespace App\Http\Controllers;

use App\Hotel;
use App\LocationDistrict;
use App\LocationDivision;
use App\User;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;

class HotelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $manager = Auth::user();
        $hotel = User::findorFail($manager->id)->hotel;
//        dd($hotel);
        if($hotel)
        {
            $division = LocationDivision::findorFail($hotel->division_id);
            $district = LocationDistrict::findorFail($hotel->district_id);
            return view('backend.manager.hotel.index',compact('hotel','district','division'));
        }
        else
        {
          return redirect()->route('hotels.create');
        }


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $divisions = LocationDivision::all();
        $districts = LocationDistrict::all();
        return view('backend.manager.hotel.create',compact("divisions","districts"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {

            $request->validate([
                'user_id' => 'required|',
                'name' => 'required',
                'division_id' => 'required|',
                'district_id' => 'required',
                'local_address' => 'required|',
                'telephone' => 'required',
                'mobile1' => 'required|',
                'mobile2' => 'required',
                'star' => 'required|',

            ]);

            $data = $request->all();

            if ($request->hasFile('photo'))
            {
                $file = $request->file('photo');
                $extension = $file->getClientOriginalExtension();
                $filename = time().'.'.$extension;
                $file->move('uploads/hotels/',$filename);
                $data['photo'] = $filename;
            }
            else{
                return $request;
                $data['photo'] = "";

            }
            Hotel::create($data);
            return redirect()->route('hotels.index')->withStatus('Task was successful!');


        }catch (QueryException $exception)
        {
            return redirect()->back()->withErrors($exception->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Hotel  $hotel
     * @return \Illuminate\Http\Response
     */
    public function show(Hotel $hotel)
   {
        $id =$hotel;
//       $hotel = App\Hotel::findorFail(1);
        $hotel = Auth::user()->hotel();
        dd($hotel) ;
//        return view('layouts.backend.manager.hotel_profile.index',compact());
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Hotel  $hotel
     * @return \Illuminate\Http\Response
     */
    public function edit(Hotel $hotel)
    {
        $DivsionForThisHotel = LocationDivision::findorFail($hotel->division_id) ;
        $DistrictForThisHotel = LocationDivision::findorFail($hotel->division_id) ;
        $divisions = LocationDivision::all();
        $districts = LocationDistrict::all();
        return view('backend.manager.hotel.edit',compact('hotel','DistrictForThisHotel','DivsionForThisHotel','districts','divisions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Hotel  $hotel
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Hotel $hotel)
    {
        try {

            $request->validate([
                'user_id' => 'required|',
                'name' => 'required',
                'division_id' => 'required|',
                'district_id' => 'required',
                'local_address' => 'required|',
                'telephone' => 'required',
                'mobile1' => 'required|',
                'mobile2' => 'required',
                'star' => 'required|',

            ]);

            $data = $request->all();
//            dd($data);
            if ($request->hasFile('photo'))
            {
                $file = $request->file('photo');
                $extension = $file->getClientOriginalExtension();
                $filename = time().'.'.$extension;
                $file->move('uploads/hotels/',$filename);
                $data['photo'] = $filename;
            }
            else{
                return $request;
                $data['photo'] = "";

            }
            $hotel->update($data);
            return redirect()->route('hotels.index')->withStatus('Task was successful!');


        }catch (QueryException $exception)
        {
            return redirect()->back()->withErrors($exception->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Hotel  $hotel
     * @return \Illuminate\Http\Response
     */
    public function destroy(Hotel $hotel)
    {
        try {


            //$hotel->delete();
            return redirect()->route('hotels.index')->withStatus('Task was successful!');


        }catch (QueryException $exception)
        {
            return redirect()->back()->withErrors($exception->getMessage());
        }
    }
}

resources/views/backend/admin/hotel/create.blade.php
@extends('backend.layouts.master_tem')
@section('content')

    <div class="container-fluid">


        <h1 style="text-align:center">Enter The Hotel Information and Complete the Hotel Profile</h1>

        <div class="container" style="margin-bottom: 20px">

            {!! Form::open(['route'=>'hotel_lists.store','files' => true]) !!}

                @include('backend.admin.hotel.form')
            <div class="form-row">
                <div class="form-group col-6">
                    <label for="photo">Hotel Picture</label>
                    <input type="file" class="form-control" name="photo" id="photo" required>

                </div>
            </div>

            <div class="form-row">
                <div class="col-4 text-center"></div>
                <div class="col-4 text-center">
                    {!! Form::submit('Register A Hotel',['class'=>['btn','btn-primary'] ]) !!}
                </div>
                <div class="col-4 text-center"></div>

            </div>


            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/backend/admin/hotel/index.blade.php
@extends('backend.layouts.master_tem')

@section('title', 'Admin: Hotels List')

@section('content')

    <h1 class="h3 mb-2 text-gray-800" style="text-align:center;">List of Hotels</h1>


    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6   class="m-0 font-weight-bold text-primary"><a href="{{ route('hotel_lists.create') }}" style="color:white;" class="btn btn-primary">Add Hotel</a></h6>
        </div>
        @if(count($hotels) == 0)
            <h3>No Record Found. Add some records</h3>
        @else
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>No.</th>
                            <th>name</th>
                            <th>Manager</th>
                            <th>Manager Mail</th>
                            <th>Phone</th>
                            <th>Division</th>
                            <th>Star</th>
                            <th>Actions</th>
                        </tr>
                        </thead>

                        <tbody>
                        @php
                            $i = 0
                        @endphp
                        @foreach($hotels as $hotel)
                            <tr>
                                <td> {{++$i}}</td>
                                <td>{{$hotel->name}}</td>
                                @php
                                $manager = \App\User::where('id','=',"$hotel->user_id")->first();

                                @endphp
                                <td>{{$manager->name}}</td>
                                <td>{{$manager->email}}</td>
                                <td>{{$hotel->mobile1}}</td>
                                @php
                                    $division = \App\LocationDivision::where('id','=',"$hotel->division_id")->first();
                                @endphp
                                <td>{{$division->name}}</td>
                                <td>{{$hotel->star}}</td>

                                <td >


                                    <a href="{{ route('hotel_lists.show', [$hotel->id]) }}" style="color:black;" class="btn btn-info">
                                        Details
                                    </a>
                                    <a href="{{ route('hotel_lists.edit', [$hotel->id]) }}" style="color:black;" class="btn btn-warning">
                                        Edit
                                    </a>

                                    <form action="{{ route('hotel_lists.destroy', [$hotel->id]) }}" method="post" style="display: inline">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" disabled class="btn btn-danger" onclick="return confirm('Are you sure want to delete ?')">Delete</button>
                                    </form>

                                    <a href="{{ route('Admin.hotel.rooms.index',[$hotel->id]) }}" style="color:white;" class="btn btn-info">Rooms</a>
                                    <a href="{{ route('Admin.hotel.booking.index',[$hotel->id]) }}" style="color:white;" class="btn btn-success">Bookings</a>

                                </td>
                            </tr>
                        @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        @endif
    </div>


@endsection

resources/views/backend/admin/hotel/show.blade.php
@extends('backend.layouts.master_tem')
@section('content')
    <h1 class="h3 mb-2 text-gray-800" style="text-align:center;">{{$hotel->name}}</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6   class="m-0 font-weight-bold text-primary">
                <a href="{{ route('hotel_lists.index' )}}" style="color:black;font-size: large" class="btn btn-info">List of Hotel</a>
                <a href="{{ route('hotel_lists.edit',[$hotel->id]) }}" style="color:black;font-size: large" class="btn btn-warning">Edit the Hotel Info </a>
            </h6>
        </div>

        <div class="container" style="margin-bottom: 20px">

            {!! Form::model($hotel) !!}


            <div class="form-row">
                <div class="form-group col-5">
                    {!! Form::label('name','Hotel name:') !!}
                    {!! Form::text('name',null,['class'=>'form-control','disabled']) !!}
                </div>

                <div class="form-group col-3">
                    {!! Form::label('manager_name','Manager name:') !!}
                    <input value="{{$manager->name}}" disabled class="form-control" id="manager_name">
                </div>
                <div class="form-group col-3">
                    {!! Form::label('manager_email','Manager Email:') !!}
                    <input value="{{$manager->email}}" disabled class="form-control" id="manager_email">
                </div>

                <div class="form-group col-1">
                    {!! Form::label('star','Hotel Star:') !!}
                    {!! Form::number('star',null,['class'=>'form-control','disabled']) !!}
                </div>
            </div>



            <div style="margin-top: 20px" >
                <strong>Hotel Location:</strong>
                <div class="form-row ">
                    <div class="form-group col">
                        <label for="id_hotel_address_division">Division:</label>
                        <input disabled class="form-control" id="id_hotel_address_division" type="text" value="{{$division->name}}">
                    </div>


                    <div class="form-group col">
                        <label for="id_hotel_address_district">District:</label>
                        <input disabled class="form-control" id="id_hotel_address_district" type="text" value="{{$district->name}}">
                    </div>
                </div>

                <div class="form-group">
                    {!! Form::label('local_address','Local Address:') !!}
                    {!! Form::text('local_address',null,['class'=>'form-control','disabled']) !!}
                </div>


            </div>
            <div style="margin-top: 20px">
                <strong>Contract Numbers</strong>
                <div class="form-row" >
                    <div class="form-group col-4">
                        {!! Form::label('telephone','Telephone No:') !!}
                        {!! Form::text('telephone',null,['class'=>'form-control','disabled']) !!}
                    </div>

                    <div class="form-group col-4">
                        {!! Form::label('mobile1','Mobile No:') !!}
                        {!! Form::text('mobile1',null,['class'=>'form-control','disabled']) !!}
                    </div>

                    <div class="form-group col-4">
                        {!! Form::label('mobile2','Another Mobile No:') !!}
                        {!! Form::text('mobile2',null,['class'=>'form-control','disabled']) !!}
                    </div>
                </div>
            </div>



            <div style="margin-top: 20px">
                <strong style="padding: 5px">Hotel Facilities</strong>
                <div class="form-row ">
                    <div class="form-group col-2 text-center" >
                        <h5>Free Breakfast</h5>
                        {!! Form::label('free_breakfast','yes') !!}
                        {!! Form::radio('free_breakfast', '1') !!}<br>
                        {!! Form::label('free_breakfast','No') !!}
                        {!! Form::radio('free_breakfast', '0') !!}
                    </div>

                    <div class="form-group col-2 text-center" >
                        <h5>Private Parking Space</h5>
                        {!! Form::label('private_parking','yes') !!}
                        {!! Form::radio('private_parking', '1') !!}<br>
                        {!! Form::label('private_parking','No') !!}
                        {!! Form::radio('private_parking', '0') !!}
                    </div>

                    <div class="form-group col-2 text-center" >
                        <h5>Car Rental Service</h5>
                        {!! Form::label('car_rental','yes') !!}
                        {!! Form::radio('car_rental', '1') !!}<br>
                        {!! Form::label('car_rental','No') !!}
                        {!! Form::radio('car_rental', '0') !!}
                    </div>

                    <div class="form-group col-2 text-center" >
                        <h5>Swimming Pool</h5>
                        {!! Form::label('swimming_pool','yes') !!}
                        {!! Form::radio('swimming_pool', '1') !!}<br>
                        {!! Form::label('swimming_pool','No') !!}
                        {!! Form::radio('swimming_pool', '0') !!}
                    </div>

                    <div class="form-group col-2 text-center" >
                        <h5>Call on Doctor</h5>
                        {!! Form::label('call_on_doctor','yes') !!}
                        {!! Form::radio('call_on_doctor', '1') !!}<br>
                        {!! Form::label('call_on_doctor','No') !!}
                        {!! Form::radio('call_on_doctor', '0') !!}
                    </div>

                    <div class="form-group col-2 text-center" >
                        <h5>Fitness Gym</h5>
                        {!! Form::label('gym','yes') !!}
                        {!! Form::radio('gym', '1')!!}<br>
                        {!! Form::label('gym','No') !!}
                        {!! Form::radio('gym', '0') !!}
                    </div>
                </div>
                <div class="form-row ">
                    <div class="form-group col-2 text-center" >
                        <h5>Restaurant In the Hotel</h5>
                        {!! Form::label('restaurant','yes') !!}
                        {!! Form::radio('restaurant', '1') !!}<br>
                        {!! Form::label('restaurant','No') !!}
                        {!! Form::radio('restaurant', '0') !!}
                    </div>

                    <div class="form-group col-2 text-center" >
                        <h5>Spas & Wellness Centers</h5>
                        {!! Form::label('spa','yes') !!}
                        {!! Form::radio('spa', '1') !!}<br>
                        {!! Form::label('spa','No') !!}
                        {!! Form::radio('spa', '0') !!}
                    </div>

                    <div class="form-group col-2 text-center" >
                        <h5>Rooms for Meeting</h5>
                        {!! Form::label('meeting_room','yes') !!}
                        {!! Form::radio('meeting_room', '1') !!}<br>
                        {!! Form::label('meeting_room','No') !!}
                        {!! Form::radio('meeting_room', '0') !!}
                    </div>

                    <div class="form-group col-3 text-center" >
                        {!! Form::label('about_breakfast','Details about Breakfast:') !!}
                        {!! Form::textarea('about_breakfast',null,['class'=>'form-control','disabled','rows'=>5,'placeholder'=>'If you offer free breakfast,please tell the details about the breakfast']) !!}

                    </div>

                    <div class="form-group col-3 text-center" >
                        {!! Form::label('other_facilities','Details of other Facilities:') !!}
                        {!! Form::textarea('other_facilities',null,['class'=>'form-control','disabled','rows'=>5,'placeholder'=>'If your hotel have other facilities,you can list the here.']) !!}

                    </div>

                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-12">
                    @if(strpos("$hotel->photo","images.unsplash.com/"))
                        <img src="{{$hotel->photo}}" style="width: 100%;height:400px" alt="">
                    @else
                        <img src='{{asset("uploads/hotels/$hotel->photo")}}' style="width: 100%;height:400px" alt="">
                    @endif
                </div>
            </div>
            <div class="form-row">
                <div class="col-12" style="text-align: center">
                    <strong>Image : {{$hotel->name}} </strong>
                </div>
            </div>



            {!! Form::close() !!}
        </div>

    </div>

@endsection