routes/web.php
<?php

use App\Hotel;
use App\LocationDistrict;
use App\LocationDivision;
use App\Role;
use App\User;
use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','CustomerController@index')->name('customer_index');
Route::get('/destinations','CustomerController@destinations')->name('customer_destinations');
Route::get('/about','CustomerController@about')->name('customer_about');
Route::get('/contract','CustomerController@contract')->name('customer_contract');
Route::get('/elements','CustomerController@elements')->name('customer_elements');
Route::get('/news','CustomerController@news')->name('customer_news');
Route::match(['get','post'],'/search','SearchController@search')->name('customer.search');
Route::match(['get','post'],'/search/show','SearchController@show')->name('customer.search.show');
Route::match(['get','post'],'/booking','CustomerBookingController@bookingPage')->name('customer.booking.index');
Route::match(['get','post'],'/booking/store','CustomerBookingController@bookingStore')->name('customer.booking.store');
Route::get('/profile/{id}','ProfileController@index')->name('profile.index');
Route::post('/profile/create','ProfileController@store')->name('profile.store');
Route::get('/profile/{id}/edit','ProfileController@edit')->name('profile.edit');

//Route::match(['get', 'post'], '/', function () {
////
//});

// manager Routes
//, 'middleware' => []

Route::get('manager/register','ManagerRegisterController@showRegistrationForm')->name('ManagerRegister');
Route::post('manager/register','ManagerRegisterController@register')->name('ManagerRegister');
Route::group(['prefix' => 'manager','middleware'=>['auth']], function()
{
    Route::get('/', 'ManagerDashboardController@index')->name('manager.dashboard.index');
    Route::resource('hotels', HotelController::class);
    Route::resource('rooms', RoomController::class);
    Route::get('/bookings/pay/{id}','BookingController@pay')->name('bookings.pay');
    Route::resource('bookings', BookingController::class);
    Route::get('/users','HotelCustomerController@index')->name('manager.customer.index');



});



// admin Routes
//, 'middleware' => []
Route::group(['prefix' => 'admin','middleware'=>['auth']], function()
{
    Route::get('/', 'AdminDashboardController@index')->name('admin.dashboard.index');
    Route::resource('divisions', 'LocationDivisionController');
    Route::resource('districts', 'LocationDistrictController');
    Route::resource('roles',RoleController::class);

    Route::get('/users/admins','UserController@admin')->name('users.admin');
    Route::get('/users/customers','UserController@customer')->name('users.customer');
    Route::get('/users/managers','UserController@manager')->name('users.manager');
    Route::resource('users',UserController::class );

    Route::resource('hotel_lists', AdminHotelController::class);
//Hotel to Room Routes
    Route::get('/hotel_lists/{id}/bookings/index/','AdminHoteltoRoomController@hotelBookings')->name('Admin.hotel.booking.index');
    Route::get('/hotel_lists/{id}/rooms/index/','AdminHoteltoRoomController@index')->name('Admin.hotel.rooms.index');
    Route::get('/hotel_lists/{id}/rooms/create','AdminHoteltoRoomController@create')->name('Admin.hotel.rooms.create');
    Route::post('/hotel_lists/{id}/rooms','AdminHoteltoRoomController@store')->name('Admin.hotel.rooms.store');
    Route::get('/hotel_lists/{id}/rooms/{room}','AdminHoteltoRoomController@show')->name('Admin.hotel.rooms.show');
    Route::get('/hotel_lists/{id}/rooms/{room}/edit','AdminHoteltoRoomController@edit')->name('Admin.hotel.rooms.edit');
    Route::put('/hotel_lists/{id}/rooms/{room}','AdminHoteltoRoomController@update')->name('Admin.hotel.rooms.update');
    Route::delete('/hotel_lists/{id}/rooms/{room}','AdminHoteltoRoomController@destroy')->name('Admin.hotel.rooms.destroy');

    Route::resource('room_lists', AdminRoomController::class);
    Route::get('/bookings','AdminBookingListController@index')->name('admin.booking.index');
});






Route::get('def','UserController@customer')->name('def');
Route::get('ghi','UserController@manager')->name('ghi');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');







// laravel default routes
//Route::get('/', function () {
//    return view('welcome');
//});



// testing and demo routes

Route::get('/testing/blade', function (Request $request) {
  return view('testing');
})->name('testing.blade');

Route::get('/testing', function (Request $request) {
    return redirect()->route('admin.booking.index');
});

//    Route::resources([
//        'hotels' => HotelController::class,
//        'hotel_facilities' => HotelFacilityController::class,
//
//
//    ]);

resources/views/backend/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title')</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <style>
        th,td
        {
            text-align: center;
        }
    </style>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
{{--                    {{ config('app.name', 'Laravel') }}--}}
                    Travelo
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->

                    <ul class="navbar-nav mr-auto">
                        @auth
                            @php
                                $user = \Illuminate\Support\Facades\Auth::user();
                                $role = \App\Role::where('id','=',"$user->role_id")->first();
                            @endphp
                            @if($role->name == "manager")
                                <li class="nav-item active">
                                    <a class="nav-link" href="{{route('manager.dashboard.index')}}">Dashboard </a>
                                </li>
                            @elseif($role->name == "admin")
                                <li class="nav-item active">
                                    <a class="nav-link" href="{{route('admin.dashboard.index')}}">Dashboard </a>
                                </li>
                            @endif

                        @endauth

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            @if($role->name == "manager")
                            <li class="nav-item active">
                                <a class="nav-link" href="{{route('hotels.index')}}">My Hotel </a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="{{route('rooms.index')}}">Rooms </a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="#">Bookings</a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="#">Payments</a>
                            </li>
                            @elseif($role->name == "admin")
                                <li class="nav-item active">
                                    <a class="nav-link" href="{{route('roles.index')}}">Roles </a>
                                </li>
                                <li class="nav-item active">
                                    <a class="nav-link" href="{{route('users.index')}}">Users </a>
                                </li>
                                <li class="nav-item active">
                                    <a class="nav-link" href="{{route('divisions.index')}}">Divisions </a>
                                </li>
                                <li class="nav-item active">
                                    <a class="nav-link" href="{{route('districts.index')}}">Districts </a>
                                </li>
                                <li class="nav-item active">
                                    <a class="nav-link" href="{{route('hotel_lists.index')}}">Hotels </a>
                                </li>
                                <li class="nav-item active">
                                    <a class="nav-link" href="{{route('room_lists.index')}}">Rooms </a>
                                </li>
                            @endif


                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @include('frontend.message')
            @include('backend.layouts.flash-message')
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/backend/layouts/flash-message.blade.php
@if ($message = Session::get('success'))

    <div class="alert alert-success alert-block">

        <button type="button" class="close" data-dismiss="alert">×</button>

        <strong>{{ $message }}</strong>

    </div>

@endif



@if ($message = Session::get('error'))

    <div class="alert alert-danger alert-block">

        <button type="button" class="close" data-dismiss="alert">×</button>

        <strong>{{ $message }}</strong>

    </div>

@endif



@if ($message = Session::get('warning'))

    <div class="alert alert-warning alert-block">

        <button type="button" class="close" data-dismiss="alert">×</button>

        <strong>{{ $message }}</strong>

    </div>

@endif



@if ($message = Session::get('info'))

    <div class="alert alert-info alert-block">

        <button type="button" class="close" data-dismiss="alert">×</button>

        <strong>{{ $message }}</strong>

    </div>

@endif



@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <button type="button" class="close" data-dismiss="alert">×</button>
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/backend/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Bookings</title>

{{--    <!-- Custom fonts for this template-->--}}
    <link href="{{asset('ui/backend/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('ui/backend/plugins/font-awesome-4.7.0/css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{asset('ui/backend/css/main_styles.css') }}">
    <link rel="stylesheet" type="text/css" href="{{asset('ui/backend/css/responsive.css') }}">
    <link rel="stylesheet" type="text/css" href="{{asset('ui/backend/plugins/OwlCarousel2-2.2.1/owl.carousel.css') }}">
    <link rel="stylesheet" type="text/css" href="{{asset('ui/backend/plugins/OwlCarousel2-2.2.1/owl.theme.default.css') }}">
    <link rel="stylesheet" type="text/css" href="{{asset('ui/backend/plugins/OwlCarousel2-2.2.1/animate.css') }}">
    <link href="{{asset('ui/backend/css/sb-admin-2.min.css') }}" rel="stylesheet">
    <link href="{{asset('ui/backend/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
    <style>
        td {
            text-align: center;
            vertical-align: middle;
        }
    </style>

</head>
<body>
<div class="super_container">
    <header>
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{--                    {{ config('app.name', 'Laravel') }}--}}
                    Travelo
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else

                            <li class="nav-item active">
                                <a class="nav-link" href="#">Rooms </a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="#">Bookings</a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="#">Payments</a>
                            </li>


                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    @yield('content')


{{--    !--footer  start-->--}}

    <footer class="footer">
        <div class="parallax_background parallax-window" data-parallax="scroll" data-image-src="{{asset('ui/frontend/images/footer_1.jpg')}}" data-speed="0.8"></div>
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="newsletter">
                        <div class="newsletter_title_container text-center">
                            <div class="newsletter_title">Subscribe to our newsletter to get the latest trends & news</div>
                            <div class="newsletter_subtitle">Join our database NOW!</div>
                        </div>
                        <div class="newsletter_form_container">
                            <form action="#" class="newsletter_form d-flex flex-md-row flex-column align-items-start justify-content-between" id="newsletter_form">
                                <div class="d-flex flex-md-row flex-column align-items-start justify-content-between">
                                    <div><input type="text" class="newsletter_input newsletter_input_name" id="newsletter_input_name" placeholder="Name" required="required"><div class="input_border"></div></div>
                                    <div><input type="email" class="newsletter_input newsletter_input_email" id="newsletter_input_email" placeholder="Your e-mail" required="required"><div class="input_border"></div></div>
                                </div>
                                <div><button class="newsletter_button">subscribe</button></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row footer_contact_row">
                <div class="col-xl-10 offset-xl-1">
                    <div class="row">

                        <!-- Footer Contact Item -->
                        <div class="col-xl-4 footer_contact_col">
                            <div class="footer_contact_item d-flex flex-column align-items-center justify-content-start text-center">
                                <div class="footer_contact_icon"><img src="{{asset('ui/frontend/images/sign.svg')}}" alt=""></div>
                                <div class="footer_contact_title">give us a call</div>
                                <div class="footer_contact_list">
                                    <ul>
                                        <li>Office Landline: +44 5567 32 664 567</li>
                                        <li>Mobile: +44 5567 89 3322 332</li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <!-- Footer Contact Item -->
                        <div class="col-xl-4 footer_contact_col">
                            <div class="footer_contact_item d-flex flex-column align-items-center justify-content-start text-center">
                                <div class="footer_contact_icon"><img src="{{asset('ui/frontend/images/trekking.svg')}}" alt=""></div>
                                <div class="footer_contact_title">come & drop by</div>
                                <div class="footer_contact_list">
                                    <ul style="max-width:190px">
                                        <li>4124 Barnes Street, Sanford, FL 32771</li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <!-- Footer Contact Item -->
                        <div class="col-xl-4 footer_contact_col">
                            <div class="footer_contact_item d-flex flex-column align-items-center justify-content-start text-center">
                                <div class="footer_contact_icon"><img src="{{asset('ui/frontend/images/around.svg')}}" alt=""></div>
                                <div class="footer_contact_title">send us a message</div>
                                <div class="footer_contact_list">
                                    <ul>
                                        <li>youremail@gmail.com</li>
                                        <li>Office@yourbusinessname.com</li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <div class="col text-center"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --> </div>
    </footer>

</div>


<script src="{{asset('ui/backend/js/jquery-3.5.1.js' )}}"></script>
<script src="{{asset('ui/backend/js/popper.js' )}} "></script>
<script src="{{asset('ui/backend/js/bootstrap.js' )}} "></script>
<script src="{{asset('ui/backend/plugins/OwlCarousel2-2.2.1/owl.carousel.js' )}} "></script>
<script src="{{asset('ui/backend/plugins/Isotope/isotope.pkgd.min.js' )}} "></script>
<script src="{{asset('ui/backend/plugins/scrollTo/jquery.scrollTo.min.js' )}} "></script>
<script src="{{asset('ui/backend/plugins/easing/easing.js' )}} "></script>
<script src="{{asset('ui/backend/plugins/parallax-js-master/parallax.min.js')}} "></script>
<script src="{{asset('ui/backend/js/custom.js' )}} "></script>
<script src="{{asset('ui/backend/js/all.min.js' )}}"></script>
<!-- Page level plugins -->
<script src="{{asset('ui/backend/datatables/jquery.dataTables.js' )}}"></script>
<script src="{{asset('ui/backend/datatables/dataTables.bootstrap4.js' )}}"></script>

<!-- Page level custom scripts -->
<script src="{{asset('ui/backend/datatables/datatables-demo.js' )}}"></script>

</body>
</html>

resources/views/backend/layouts/master_tem.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> @yield('title')</title>

    <!-- Custom fonts for this template-->
    <link href="{{ asset('ui/backend') }}/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{{ asset('ui/backend') }}/css/sb-admin-2.min.css" rel="stylesheet">

    @stack('css')
</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

    @include('backend.layouts.partials.navbar')

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            @include('backend.layouts.partials.tob-bar')

            <!-- Begin Page Content -->
            <div class="container-fluid text-dark">
                @include('backend.layouts.flash-message')
                @yield('content')

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
        @include('backend.layouts.partials.footer')
        <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="login.html">Logout</a>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="{{ asset('ui/backend') }}/jquery/jquery.min.js"></script>
<script src="{{ asset('ui/backend') }}/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="{{ asset('ui/backend') }}/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
<script src="{{ asset('ui/backend') }}/js/sb-admin-2.min.js"></script>

@stack('js')

</body>

</html>